#!/bin/bash -eu
#
#  Tests for FernetCrypt

if [ -d .git ]; then
  FERNETCRYPT=$(pwd)/fernetcrypt
  TESTDIR=$(pwd)/tests
else
  FERNETCRYPT=$(pwd)/../fernetcrypt
  TESTDIR=$(pwd)
fi
export FERNETCRYPT
export TESTDIR

cd "$TESTDIR"
for TEST in test_*; do
  cd "$TESTDIR"
  [ ! -f "$TEST"/run_test ] && continue
  cd "$TESTDIR"/"$TEST"
  echo "*** $TEST ***"
  if ! ./run_test; then
    echo "!!! TEST FAILED"
    exit 1
  fi
done

exit "$?"
