#!/bin/bash -eu
#
#  Test the basics

PASSWORD=foobar
SRC=$(mktemp)
DST=$(mktemp)
trap "rm -f $SRC $DST" exit

date >"$SRC"

BEFORE=$(sha1sum <$SRC)
$FERNET --password "$PASSWORD" encrypt "$SRC" "$DST"
: >"$SRC"
$FERNET --password "$PASSWORD" decrypt "$DST" "$SRC"
AFTER=$(sha1sum <$SRC)
if [ "$BEFORE" != "$AFTER" ]; then
  echo "Encryption/decryption failed, $BEFORE != $AFTER"
  exit 1
fi

$FERNET --raw --password "$PASSWORD" encrypt "$SRC" "$DST"
: >"$SRC"
$FERNET --raw --password "$PASSWORD" decrypt "$DST" "$SRC"
AFTER=$(sha1sum <$SRC)

if [ "$BEFORE" != "$AFTER" ]; then
  echo "Encryption/decryption failed, $BEFORE != $AFTER"
  exit 1
fi

exit 0
