#!/bin/bash -euxv
#
#  Test the basics

PASSWORD=foobar
SRC=$(mktemp)
DST=$(mktemp)
trap "rm -f $SRC $DST" exit

date >"$SRC"

BEFORE=$(sha1sum <$SRC)
$FERNETCRYPT encrypt --password "$PASSWORD" "$SRC" "$DST"
: >"$SRC"
$FERNETCRYPT decrypt --password "$PASSWORD" "$DST" "$SRC"
AFTER=$(sha1sum <$SRC)
if [ "$BEFORE" != "$AFTER" ]; then
  echo "Encryption/decryption failed, $BEFORE != $AFTER"
  exit 1
fi

$FERNETCRYPT encrypt --raw --password "$PASSWORD" "$SRC" "$DST"
: >"$SRC"
$FERNETCRYPT decrypt --raw --password "$PASSWORD" "$DST" "$SRC"
AFTER=$(sha1sum <$SRC)

if [ "$BEFORE" != "$AFTER" ]; then
  echo "Encryption/decryption failed, $BEFORE != $AFTER"
  exit 1
fi

exit 0
